name: needOnJonBug
on:
  push:
  workflow_dispatch:

jobs:
  Job1:
    name: Job 1
    runs-on: ubuntu-ne-latest
    steps:
      - name: sleep
        run: echo job 1 almost done

  Job2:
    needs: ${{ github.actor }}"
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: echo job 2 almost done

  Job3:
    needs: Job1
    name: Job 3
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: echo job 3 almost done
